{{- $fullName := include "foos.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "foos.fullname" . }}
  labels:
    {{- include "foos.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "foos.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "foos.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "foos.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- if or (.Values.config) (.Values.secrets) }}
          envFrom:
            {{- if .Values.config }}
            - configMapRef:
                name: {{$fullName}}-configmap
            {{- end }}
            {{- if .Values.secrets }}
            - secretRef:
                name: {{$fullName}}-secrets
            {{- end }}
            {{- if .Values.configMapNames}}
              {{- range .Values.configMapNames }}
              - configMapRef:
                  name: {{.}}
              {{- end }}
            {{- end }}
            {{- if .Values.secretNames}}
              {{- range .Values.secretNames }}
              - secretRef:
                  name: {{.}}
              {{- end }}
            {{- end }}
          {{- end }}              
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
