{{- $fullName := include "foos.fullname" . -}}
{{ if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-secrets
type: Opaque
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key | upper }}: {{ $val | b64enc }}
  {{- end }} 
{{ end }}