config:
  PORT: 80
  MYSQL_HOST: arasoft-mysql-01-ams3-do-user-8079416-0.b.db.ondigitalocean.com
  MYSQL_PORT: 25060
  MYSQL_USER: foos
  MYSQL_DBNAME: foos-readmodels
  EVENTSTORE_MYSQL_HOST: arasoft-mysql-01-ams3-do-user-8079416-0.b.db.ondigitalocean.com
  EVENTSTORE_MYSQL_PORT: 25060
  EVENTSTORE_MYSQL_USER: foos
  EVENTSTORE_MYSQL_DBNAME: foos-events

ingress:
  enabled: true 
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: cert-manager-webhook-dnsimple-production
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
  hosts:
    - host: foos.app
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: foos-appara-name-tls
      hosts:
        - foos.app 