FROM nginx

COPY ./conf.d/ /etc/nginx/conf.d/

COPY ./html/backend-not-found.html /var/www/html/backend-not-found.html

COPY ./includes/ /etc/nginx/includes/

COPY ./ssl/ /etc/ssl/certs/nginx/